### ISSUE TITLE
concurrent map read/write

### ISSUE THREAD

**Issue by kalexmills** [Frabjous-Studios/ldjam-53#9]
```
fatal error: concurrent map read and map write

goroutine 63 [running]:
github.com/DrJosh9000/yarn.MapVariableStorage.GetValue(0x1031a5aa0?, {0x14000daba28?, 0x14000dab9e0?})
        /Users/kalexmills/go/pkg/mod/github.com/!dr!josh9000/yarn@v0.5.0/vars.go:36 +0x34
github.com/DrJosh9000/yarn.(*VirtualMachine).execPushVariable(0x14001328880, {0x14000d63ce8?, 0x1?, 0x14000dc08c0?})
        /Users/kalexmills/go/pkg/mod/github.com/!dr!josh9000/yarn@v0.5.0/vm.go:597 +0x90
github.com/DrJosh9000/yarn.(*VirtualMachine).execute(0x0?, 0x0?)
        /Users/kalexmills/go/pkg/mod/github.com/!dr!josh9000/yarn@v0.5.0/vm.go:228 +0x9c
github.com/DrJosh9000/yarn.(*VirtualMachine).Run(0x14001328880, {0x1027a4807, 0x15})
        /Users/kalexmills/go/pkg/mod/github.com/!dr!josh9000/yarn@v0.5.0/vm.go:186 +0x3bc
github.com/Frabjous-Studios/bankwave/internal.(*DialogueRunner).DoNode(0x14000301730, {0x1027a4807, 0x15})
        /Users/kalexmills/repos/personal/ldjam-53/internal/dialogue_runner.go:94 +0xb4
github.com/Frabjous-Studios/bankwave/internal.(*MainScene).startRunner.func1()
        /Users/kalexmills/repos/personal/ldjam-53/internal/main_scene.go:802 +0x30
created by github.com/Frabjous-Studios/bankwave/internal.(*MainScene).startRunner
        /Users/kalexmills/repos/personal/ldjam-53/internal/main_scene.go:801 +0x134

goroutine 1 [select, locked to thread]:
github.com/hajimehoshi/ebiten/v2/internal/thread.(*OSThread).Loop(0x140009a9280, {0x10323bcd0, 0x140009038b0})
        /Users/kalexmills/go/pkg/mod/github.com/hajimehoshi/ebiten/v2@v2.6.0-alpha.2.0.20230501101708-d16b591a352b/internal/thread/thread.go:44 +0xb4
github.com/hajimehoshi/ebiten/v2/internal/ui.(*userInterfaceImpl).Run(0x1035fa780, {0x10323e1b0?, 0x14000992a80}, 0x103209220?)
        /Users/kalexmills/go/pkg/mod/github.com/hajimehoshi/ebiten/v2@v2.6.0-alpha.2.0.20230501101708-d16b591a352b/internal/ui/run_glfw_notsinglethread.go:61 +0x3f8
github.com/hajimehoshi/ebiten/v2.RunGameWithOptions({0x10323a650, 0x140009929a0}, 0x0)
        /Users/kalexmills/go/pkg/mod/github.com/hajimehoshi/ebiten/v2@v2.6.0-alpha.2.0.20230501101708-d16b591a352b/run.go:305 +0x154
github.com/hajimehoshi/ebiten/v2.RunGame(...)
        /Users/kalexmills/go/pkg/mod/github.com/hajimehoshi/ebiten/v2@v2.6.0-alpha.2.0.20230501101708-d16b591a352b/run.go:229
main.main()
        /Users/kalexmills/repos/personal/ldjam-53/cmd/game/main.go:27 +0xe4

goroutine 6 [select, locked to thread]:
github.com/hajimehoshi/ebiten/v2/internal/thread.(*OSThread).Loop(0x140009a9290, {0x10323bcd0, 0x140009038b0})
        /Users/kalexmills/go/pkg/mod/github.com/hajimehoshi/ebiten/v2@v2.6.0-alpha.2.0.20230501101708-d16b591a352b/internal/thread/thread.go:44 +0xb4
github.com/hajimehoshi/ebiten/v2/internal/ui.(*userInterfaceImpl).Run.func1()
        /Users/kalexmills/go/pkg/mod/github.com/hajimehoshi/ebiten/v2@v2.6.0-alpha.2.0.20230501101708-d16b591a352b/internal/ui/run_glfw_notsinglethread.go:50 +0x50
golang.org/x/sync/errgroup.(*Group).Go.func1()
        /Users/kalexmills/go/pkg/mod/golang.org/x/sync@v0.1.0/errgroup/errgroup.go:75 +0x5c
created by golang.org/x/sync/errgroup.(*Group).Go
        /Users/kalexmills/go/pkg/mod/golang.org/x/sync@v0.1.0/errgroup/errgroup.go:72 +0xa0

goroutine 7 [runnable]:
github.com/hajimehoshi/ebiten/v2/internal/restorable.(*Image).makeStale(0x14001aa8200, {{0xc9?, 0x0?}, {0x5c9?, 0x3c0?}})
        /Users/kalexmills/go/pkg/mod/github.com/hajimehoshi/ebiten/v2@v2.6.0-alpha.2.0.20230501101708-d16b591a352b/internal/restorable/image.go:225 +0x1ac
github.com/hajimehoshi/ebiten/v2/internal/restorable.(*Image).DrawTriangles(0x14001aa8200, {0x140000beb80, 0x0, 0x0, 0x0}, {{0x0, 0x0}, {0x0, 0x0}, {0x0, ...}}, ...)
        /Users/kalexmills/go/pkg/mod/github.com/hajimehoshi/ebiten/v2@v2.6.0-alpha.2.0.20230501101708-d16b591a352b/internal/restorable/image.go:364 +0x238
github.com/hajimehoshi/ebiten/v2/internal/atlas.(*Image).drawTriangles(0x140009c42c0, {0x140001705c0, 0x0, 0x0, 0x0}, {0x140004b2380, 0x20, 0x20}, {0x10351a540, 0x6, ...}, ...)
        /Users/kalexmills/go/pkg/mod/github.com/hajimehoshi/ebiten/v2@v2.6.0-alpha.2.0.20230501101708-d16b591a352b/internal/atlas/image.go:504 +0x64c
github.com/hajimehoshi/ebiten/v2/internal/atlas.(*Image).DrawTriangles(0x0?, {0x140001705c0, 0x0, 0x0, 0x0}, {0x140004b2380?, 0x10351a540?, 0x0?}, {0x10351a540?, 0x5050101?, ...}, ...)
        /Users/kalexmills/go/pkg/mod/github.com/hajimehoshi/ebiten/v2@v2.6.0-alpha.2.0.20230501101708-d16b591a352b/internal/atlas/image.go:419 +0x1c4
github.com/hajimehoshi/ebiten/v2/internal/buffered.(*Image).drawTrianglesImpl(0x0?, {0x14000303050, 0x0, 0x0, 0x0}, {0x140004b2380?, 0x10351a540?, 0x0?}, {0x10351a540?, 0x10253fbf8?, ...}, ...)
        /Users/kalexmills/go/pkg/mod/github.com/hajimehoshi/ebiten/v2@v2.6.0-alpha.2.0.20230501101708-d16b591a352b/internal/buffered/image.go:185 +0x164
github.com/hajimehoshi/ebiten/v2/internal/buffered.(*Image).DrawTriangles(0x14000a315c0?, {0x14000303050, 0x0, 0x0, 0x0}, {0x140004b2380?, 0x10351a540?, 0x20?}, {0x10351a540?, 0x5050101?, ...}, ...)
        /Users/kalexmills/go/pkg/mod/github.com/hajimehoshi/ebiten/v2@v2.6.0-alpha.2.0.20230501101708-d16b591a352b/internal/buffered/image.go:172 +0x3a0
github.com/hajimehoshi/ebiten/v2/internal/mipmap.(*Mipmap).DrawTriangles(0x14000a31620, {0x14000303080, 0x0, 0x0, 0x0}, {0x140004b2380?, 0x20, 0x20}, {0x10351a540?, 0x6, ...}, ...)
        /Users/kalexmills/go/pkg/mod/github.com/hajimehoshi/ebiten/v2@v2.6.0-alpha.2.0.20230501101708-d16b591a352b/internal/mipmap/mipmap.go:127 +0x218
github.com/hajimehoshi/ebiten/v2/internal/ui.(*Image).DrawTriangles(0x14000a3dd60, {0x14000180370, 0x0, 0x0, 0x0}, {0x140004b2380, 0x20, 0x20}, {0x10351a540, 0x6, ...}, ...)
        /Users/kalexmills/go/pkg/mod/github.com/hajimehoshi/ebiten/v2@v2.6.0-alpha.2.0.20230501101708-d16b591a352b/internal/ui/image.go:116 +0x388
github.com/hajimehoshi/ebiten/v2.(*Image).DrawImage(0x14000300850, 0x140002ae4d0, 0x0?)
        /Users/kalexmills/go/pkg/mod/github.com/hajimehoshi/ebiten/v2@v2.6.0-alpha.2.0.20230501101708-d16b591a352b/image.go:271 +0x76c
github.com/kalexmills/asebiten.(*Animation).DrawTo(...)
        /Users/kalexmills/go/pkg/mod/github.com/kalexmills/asebiten@v0.4.3/asebiten.go:177
github.com/Frabjous-Studios/bankwave/internal.(*Shredder).DrawTo(0x14000987fe0?, 0x1032389b8?)
        /Users/kalexmills/repos/personal/ldjam-53/internal/shredder.go:49 +0x128
github.com/Frabjous-Studios/bankwave/internal.(*MainScene).Draw(0x14000356400, 0x0?)
        /Users/kalexmills/repos/personal/ldjam-53/internal/main_scene.go:642 +0x1c4
github.com/Frabjous-Studios/bankwave/internal.(*Game).Draw(0x0?, 0x0?)
        /Users/kalexmills/repos/personal/ldjam-53/internal/game.go:126 +0x28
github.com/hajimehoshi/ebiten/v2.(*gameForUI).DrawOffscreen(0x14000992a80)
        /Users/kalexmills/go/pkg/mod/github.com/hajimehoshi/ebiten/v2@v2.6.0-alpha.2.0.20230501101708-d16b591a352b/gameforui.go:161 +0x34
github.com/hajimehoshi/ebiten/v2/internal/ui.(*context).drawGame(0x140001c0c40, {0x103240148, 0x14000392480}, 0x0)
        /Users/kalexmills/go/pkg/mod/github.com/hajimehoshi/ebiten/v2@v2.6.0-alpha.2.0.20230501101708-d16b591a352b/internal/ui/context.go:187 +0xf0
github.com/hajimehoshi/ebiten/v2/internal/ui.(*context).updateFrameImpl(0x140001c0c40, {0x103240148, 0x14000392480}, 0x1, 0x4084000000000000, 0x407e000000000000, 0x14000030d80?, 0x1035fa780, 0x1?)
        /Users/kalexmills/go/pkg/mod/github.com/hajimehoshi/ebiten/v2@v2.6.0-alpha.2.0.20230501101708-d16b591a352b/internal/ui/context.go:155 +0x330
github.com/hajimehoshi/ebiten/v2/internal/ui.(*context).updateFrame(0x140009a9280?, {0x103240148, 0x14000392480}, 0xc10cc4ad5db51e28?, 0x45a6a567a3?, 0x1035f9f20?, 0x0?)
        /Users/kalexmills/go/pkg/mod/github.com/hajimehoshi/ebiten/v2@v2.6.0-alpha.2.0.20230501101708-d16b591a352b/internal/ui/context.go:73 +0x60
github.com/hajimehoshi/ebiten/v2/internal/ui.(*userInterfaceImpl).updateGame(0x1035fa780)
        /Users/kalexmills/go/pkg/mod/github.com/hajimehoshi/ebiten/v2@v2.6.0-alpha.2.0.20230501101708-d16b591a352b/internal/ui/ui_glfw.go:1084 +0x1c8
github.com/hajimehoshi/ebiten/v2/internal/ui.(*userInterfaceImpl).loopGame(0x1035fa780)
        /Users/kalexmills/go/pkg/mod/github.com/hajimehoshi/ebiten/v2@v2.6.0-alpha.2.0.20230501101708-d16b591a352b/internal/ui/ui_glfw.go:1044 +0x7c
github.com/hajimehoshi/ebiten/v2/internal/ui.(*userInterfaceImpl).Run.func2()
        /Users/kalexmills/go/pkg/mod/github.com/hajimehoshi/ebiten/v2@v2.6.0-alpha.2.0.20230501101708-d16b591a352b/internal/ui/run_glfw_notsinglethread.go:57 +0x3c
golang.org/x/sync/errgroup.(*Group).Go.func1()
        /Users/kalexmills/go/pkg/mod/golang.org/x/sync@v0.1.0/errgroup/errgroup.go:75 +0x5c
created by golang.org/x/sync/errgroup.(*Group).Go
        /Users/kalexmills/go/pkg/mod/golang.org/x/sync@v0.1.0/errgroup/errgroup.go:72 +0xa0

goroutine 8 [sync.Cond.Wait]:
sync.runtime_notifyListWait(0x14000844310, 0x7882)
        /usr/local/go/src/runtime/sema.go:527 +0x16c
sync.(*Cond).Wait(0x14000844300)
        /usr/local/go/src/sync/cond.go:70 +0xd0
github.com/hajimehoshi/oto/v2/internal/mux.(*Mux).wait(0x14000844340)
        /Users/kalexmills/go/pkg/mod/github.com/hajimehoshi/oto/v2@v2.5.0-alpha.0.20230315035531-31c83ff4311d/internal/mux/mux.go:86 +0x90
github.com/hajimehoshi/oto/v2/internal/mux.(*Mux).loop(0x14000844340)
        /Users/kalexmills/go/pkg/mod/github.com/hajimehoshi/oto/v2@v2.5.0-alpha.0.20230315035531-31c83ff4311d/internal/mux/mux.go:93 +0x48
created by github.com/hajimehoshi/oto/v2/internal/mux.New
        /Users/kalexmills/go/pkg/mod/github.com/hajimehoshi/oto/v2@v2.5.0-alpha.0.20230315035531-31c83ff4311d/internal/mux/mux.go:68 +0x10c

goroutine 12 [runnable]:
github.com/Frabjous-Studios/bankwave/internal.(*MainScene).startDialogueReceivers.func1()
        /Users/kalexmills/repos/personal/ldjam-53/internal/main_scene.go:177 +0x40
created by github.com/Frabjous-Studios/bankwave/internal.(*MainScene).startDialogueReceivers
        /Users/kalexmills/repos/personal/ldjam-53/internal/main_scene.go:176 +0x60

goroutine 21 [sync.Cond.Wait]:
sync.runtime_notifyListWait(0x14000844250, 0x699b)
        /usr/local/go/src/runtime/sema.go:527 +0x16c
sync.(*Cond).Wait(0x14000844240)
        /usr/local/go/src/sync/cond.go:70 +0xd0
github.com/hajimehoshi/oto/v2.(*context).wait(0x140009fe140)
        /Users/kalexmills/go/pkg/mod/github.com/hajimehoshi/oto/v2@v2.5.0-alpha.0.20230315035531-31c83ff4311d/driver_darwin.go:153 +0x8c
github.com/hajimehoshi/oto/v2.(*context).loop(0x140009fe140)
        /Users/kalexmills/go/pkg/mod/github.com/hajimehoshi/oto/v2@v2.5.0-alpha.0.20230315035531-31c83ff4311d/driver_darwin.go:161 +0x64
created by github.com/hajimehoshi/oto/v2.newContext.func1
        /Users/kalexmills/go/pkg/mod/github.com/hajimehoshi/oto/v2@v2.5.0-alpha.0.20230315035531-31c83ff4311d/driver_darwin.go:142 +0x220
exit status 2
```

**Comment by kalexmills** [comment]
I have a workaround for now where we just don't check the Vars -- this isn't required for _this_ game, at least.
